#!/bin/bash

SCRIPT_PATH=$( dirname $( readlink -f $0 ))
ELECTRON=${SCRIPT_PATH}/node_modules/electron/dist/electron
APP=${SCRIPT_PATH}/electrify-me

if [ ! -f ${ELECTRON} ]; then
    echo "Electron not yet installed. Will run npm..."
    npm install
fi

CMDLINE="$ELECTRON --enable-transparent-visuals --disable-gpu $APP $@"

echo "SCRIPT   - $SCRIPT_PATH"
echo "ELECTRON - $ELECTRON"
echo "APP      - $APP"
echo "COMMAND  - $CMDLINE"

eval "$CMDLINE" &
