#!/bin/bash

SCRIPT_PATH=$( dirname $( readlink -f $0 ))
ELECTRON=${SCRIPT_PATH}/node_modules/electron/dist/electron
APP=${SCRIPT_PATH}/electrify-me
cd $SCRIPT_PATH

[ ! -f ${ELECTRON} ] && {
    printf "Electron not yet installed. "
    cd $SCRIPT_PATH
    [ -z $( command -v yarn ) ] && {
        printf "Running npm... "
        npm install &> /dev/null
    } || {
        printf "Running yarn... "
        yarn install &> /dev/null
    }
    printf "done!\n"
}

# printf "ROOT     - ${SCRIPT_PATH}\n"
# printf "ELECTRON - ${ELECTRON}\n"
# printf "APP      - ${APP}\n"

$ELECTRON . $@
